name: Build Windows Executable

on:
  release:
    types: [prereleased]
  push:
    branches:
      - main
    paths:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/*.yml"

permissions: write-all

jobs:
  build-windows:
    name: Build for Windows
    # 固定在 Windows 环境运行
    runs-on: windows-latest

    strategy:
      matrix:
        # 只定义需要构建的 Windows 架构
        goarch: [amd64, 386, arm64]

    env:
      # 固定目标平台为 Windows
      GOOS: windows
      GOARCH: ${{ matrix.goarch }}
      CGO_ENABLED: 0

    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ^1.21

      - name: Get project dependencies
        run: go mod download

      - name: Build Windows Executable
        shell: pwsh
        run: |
          # 创建一个目录存放构建产物
          mkdir build_assets
          # 直接编译成 .exe 文件
          go build -v -o build_assets/EasierConnect.exe -trimpath -ldflags "-s -w -buildid=" .

      - name: Create ZIP archive
        shell: pwsh
        run: |
          $ASSET_NAME = "windows-${{ matrix.goarch }}"
          Compress-Archive -Path ./build_assets/* -DestinationPath ./EasierConnect-${ASSET_NAME}.zip -Force
          echo "ASSET_PATH=./EasierConnect-${ASSET_NAME}.zip" | Add-Content -Path $env:GITHUB_ENV
          echo "ASSET_NAME=EasierConnect-${ASSET_NAME}.zip" | Add-Content -Path $env:GITHUB_ENV

      - name: Upload artifact for all runs
        uses: actions/upload-artifact@v4
        with:
          name: EasierConnect-windows-${{ matrix.goarch }}
          path: ${{ env.ASSET_PATH }}

      - name: Upload binary to Release
        if: github.event_name == 'release'
        env:
          GITHUB_TOKEN: ${{ github.token }}
        shell: pwsh
        run: |
          gh release upload ${{ github.event.release.tag_name }} ${{ env.ASSET_PATH }}
